def GIR_REPO_URL = 'https://github.com/oprokipchuk/backend-sandbox'

pipeline {
    agent {
        docker {
            image 'maven:3.9.4'
            args '-u root'
        }
    }

    stages {
        stage('Build') {
            steps {
                dir('domainless/hello-world') {
                    sh 'mvn --no-transfer-progress clean install'
                }
            }
        }
    }

    post {
        success {
            echo 'Build successful!'
        }

        failure {
            echo 'Build failed!'
        }
    }
}
